# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: "Ubuntu-latest"

trigger:
  - master

variables:
  buildConfiguration: "Release"

steps:
  # install sdk .net 9.0
  - task: UseDotNet@2
    displayName: 'Use .NET SDK 9.x'
    inputs:
      packageType: 'sdk'
      version: '9.x'

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet Build'

  - script: dotnet pack --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    displayName: 'dotnet Pack'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
